//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventForYou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Event { get; set; }
        public Nullable<int> User { get; set; }
        public Nullable<int> Event_Manager { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Event_Managers Event_Managers { get; set; }
        public virtual Events Events { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
